db_path: ../kcov_coverage.db
kcov_runner_path: ../kcov_runner
kcov_timeout: 30
log_level: INFO
lookup_table_cache: ../cache/pc_lookup_table.txt
parallel_workers: 4
result_dir: ../path_results
testcase_dir: ../testcases
use_llvm_symbolizer: true
verifier_end_addr: '0xffffffff81e17390'
verifier_start_addr: '0xffffffff81dcd390'
vmlinux_path: ../vmlinux
