#!/usr/bin/env python3
import os
import re
import subprocess
import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from utils.config import DEFAULT_CONFIG_PATH, load_project_config

def parse_verifier_log(log_path):
    """
    Parses the verifier log to extract the visited PC sequence (indices).
    Returns a set of visited indices.
    """
    visited = set()
    try:
        with open(log_path, 'r') as f:
            for line in f:
                # Verifier log lines for instructions look like:
                # 0: (b7) r1 = 0
                # 11: (b7) r2 = 0
                m = re.match(r'^(\d+):\s+\([0-9a-fA-F]+\)', line.strip())
                if m:
                    idx = int(m.group(1))
                    visited.add(idx)
    except FileNotFoundError:
        print(f"Error: Log file not found at {log_path}", file=sys.stderr)
        return None
    return visited

def is_instruction(clean_line):
    code_part = clean_line.split('#', 1)[0].strip()
    if not code_part:
        return False
    if code_part.startswith('.'):
        return False
    if code_part.endswith(':'):
        return False
    return True

def parse_assembly(asm_path):
    """
    Parses the BPF assembly file generated by clang -S.
    Returns:
      lines: the original lines of the file.
      inst_mapping: list of (line_index, opcode_type) for actual instructions.
    """
    with open(asm_path, 'r') as f:
        lines = f.readlines()
        
    inst_mapping = []
    for i, line in enumerate(lines):
        clean_line = line.strip()
        if not is_instruction(clean_line):
            continue
        # Check if it's a 64-bit load (requires 2 slots in BPF)
        # Typically looks like 'r1 = 18 ll' or something similar
        is_64bit_load = False
        if "ll" in clean_line and "=" in clean_line:
            is_64bit_load = True
        inst_mapping.append((i, is_64bit_load))
        
    return lines, inst_mapping

def reduce_assembly(lines, inst_mapping, visited_indices):
    """
    Reduces the assembly lines by comparing instruction indices to visited set.
    """
    kept_lines = []
    
    current_inst_idx = 0
    # Create a mapping from line_index to BPF instruction index (or multiple if 64-bit)
    line_to_bpf_idx = {}
    
    for line_idx, is_64bit in inst_mapping:
        line_to_bpf_idx[line_idx] = current_inst_idx
        if is_64bit:
            current_inst_idx += 2
        else:
            current_inst_idx += 1
            
    # Now build the new lines
    for i, line in enumerate(lines):
        clean_line = line.strip()
        
        if clean_line.startswith(".Lfunc_end"):
            kept_lines.append("\texit    # Padding to keep forward jumps valid\n")
            
        if not is_instruction(clean_line):
            kept_lines.append(line)
            continue
            
        bpf_idx = line_to_bpf_idx[i]
        # Check if this BPF index was visited
        if bpf_idx in visited_indices:
            kept_lines.append(line)
        else:
            kept_lines.append(f"    # Trimmed: {line.strip()} (unexecuted)\n")
            
    return kept_lines

def run_reduction(c_file, out_dir, vm_ssh_key, vm_port=10086, vm_host="127.0.0.1"):
    import shutil
    base_name = os.path.basename(c_file)
    name_no_ext, _ = os.path.splitext(base_name)
    dir_name = os.path.dirname(c_file) or '.'
    
    asm_file = os.path.join(dir_name, f"tmp_{name_no_ext}.s")
    obj_file = os.path.join(dir_name, f"tmp_{name_no_ext}.o")
    reduced_asm_file = os.path.join(dir_name, f"tmp_re_{name_no_ext}.s")
    
    final_normal_obj = os.path.join(out_dir, f"{name_no_ext}.o")
    final_reduced_obj = os.path.join(out_dir, f"re_{name_no_ext}.o")
    
    host_log_path = os.path.join(dir_name, f"tmp_verifier_{name_no_ext}.log")
    
    print(f"\n[*] Processing {c_file}...")
    
    # 1. Compile C to Assembly on host
    cmd = ["clang", "-O2", "-g", "-target", "bpf", "-c", c_file, "-S", "-o", asm_file]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # 2. Compile Assembly to Object on host
    cmd = ["clang", "-O2", "-g", "-target", "bpf", "-c", asm_file, "-o", obj_file]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # 3. Request verifier log from the VM
    abs_obj_path = os.path.abspath(obj_file)
    rel_path = os.path.relpath(abs_obj_path, os.getcwd())
    vm_obj_path = f"/mnt/root/{rel_path}"
    
    ssh_cmd = [
        "ssh", "-q", "-o", "StrictHostKeyChecking no", "-i", vm_ssh_key, f"-p", str(vm_port), f"root@{vm_host}",
        f"LD_LIBRARY_PATH=/mnt/root /mnt/root/kcov_runner {vm_obj_path}"
    ]
    
    with open(host_log_path, "w") as f:
        subprocess.run(ssh_cmd, stdout=f, stderr=f)
    
    if not os.path.exists(host_log_path):
        print(f"[!] Verifier log not generated at {host_log_path}")
        return
        
    visited = parse_verifier_log(host_log_path)
    if not visited:
        print(f"[!] Program already accepted perfectly. Keeping original compilation -> {final_normal_obj}")
        shutil.copy(obj_file, final_normal_obj)
        for f in [asm_file, obj_file, host_log_path, reduced_asm_file]:
            if os.path.exists(f): os.remove(f)
        return
    else:
        print(f"[*] Found {len(visited)} executed instruction blocks.")
        
    # 4. Filter assembly
    lines, inst_mapping = parse_assembly(asm_file)
    kept_lines = reduce_assembly(lines, inst_mapping, visited)
    
    with open(reduced_asm_file, 'w') as f:
        f.writelines(kept_lines)
        
    # 5. Compile reduced object
    cmd = ["clang", "-O2", "-g", "-target", "bpf", "-c", reduced_asm_file, "-o", final_reduced_obj]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # Cleanup intermediate files
    for f in [asm_file, obj_file, reduced_asm_file, host_log_path]:
        if os.path.exists(f): os.remove(f)
        
    print(f"[+] Successfully reduced! Created: {final_reduced_obj}")

def batch_process(in_dir, out_dir, vm_ssh_key, vm_port, vm_host):
    os.makedirs(out_dir, exist_ok=True)
    c_files = [os.path.join(in_dir, f) for f in os.listdir(in_dir) if f.endswith('.c')]
    if not c_files:
        print(f"[!] No .c files found in {in_dir}")
        return
        
        print(f"[*] Processing {len(c_files)} testcases from {in_dir} to {out_dir}")
    for c_file in sorted(c_files):
        try:
            run_reduction(c_file, out_dir, vm_ssh_key, vm_port=vm_port, vm_host=vm_host)
        except Exception as e:
            print(f"[!] Errored on {c_file}: {e}")

if __name__ == "__main__":
    config = load_project_config()
    parser = argparse.ArgumentParser(description="Trim unexecuted BPF instructions from a testcase based on verifier log.")
    parser.add_argument("-i", "--input-dir", required=True, help="Input directory containing .c files")
    parser.add_argument("-o", "--output-dir", required=True, help="Output directory for reduced .o files")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG_PATH), help="Path to project config YAML")
    parser.add_argument("--key", default=None, help="Optional override for config.vm_ssh_key")
    parser.add_argument("--port", type=int, default=None, help="Optional override for config.vm_ssh_port")
    parser.add_argument("--host", default=None, help="Optional override for config.vm_ssh_host")
    args = parser.parse_args()
    config = load_project_config(args.config)
    host = args.host or config.vm_ssh_host.replace("root@", "")
    batch_process(args.input_dir, args.output_dir, args.key or config.vm_ssh_key, args.port or config.vm_ssh_port, host)
